<?php ob_start(); ?>

<table class="table table-strepid">
    <tr class="table-dark">
        <td>Id</td>
        <td>Pseudo</td>
        <td>Nom</td>
        <td>Prenom</td>
        <td>Email</td>
        <td>Civilité</td>
        <td>Statut</td>
        <td>Date enregistrement</td>
        <td>Action</td>
    </tr>

    <?php foreach ($membres as $membre): ?>
        <tr>
            <td> <?= $membre->getId_membre(); ?></td>
            <td> <?= $membre->getPseudo(); ?></td>
            <td> <?= $membre->getNom(); ?></td>
            <td> <?= $membre->getPrenom(); ?></td>
            <td> <?= $membre->getEmail(); ?></td>
            <td> <?= $membre->getCivilte(); ?></td>
            <td> <?= $membre->getStatut(); ?></td>
            <td> <?= $membre->getDate_enregistrement(); ?></td>
            <td>
                <a href="#">voir</a>
                <a href="#">Modifier</a>
                <a href="#">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

    <form action="" method="post">
        <div class="row">
            <div class="col-6 mt-4">
                <label for="pseudo">Pseudo</label>
                <input type="text" name="pseudo" class="form-control" placeholder="Pseudo">
            </div>
            <div class="col-6 mt-4">
                <label for="email">Votre email</label>
                <input type="email" name="email" class="form-control" placeholder="Email">
            </div>
            <div class="col-6 mt-4">
                <label for="mdp">Mot de passe</label>
                <input type="password" name="mdp" class="form-control" >
            </div>
            <div class="col-6 mt-4">
                <label for="civilte">Civilité</label>
                <select name="civilte" class="form-select">
                    <option value="homme">homme</option>
                    <option value="femme">femme</option>
                </select>
            </div>
            <div class="col-6 mt-4">
                <label for="nom">Votre nom</label>
                <input type="text" name="nom" class="form-control" placeholder="Nom">
            </div>
            
            <div class="col-6 mt-4">
                <label for="prenom">Votre prénom</label>
                <input type="text" name="prenom" class="form-control" placeholder="Prénom">
            </div> 
             <div class="col-6 mt-4">
                <label for="statut">Statut</label>
                <select name="statut" class="form-select">
                    <option value="1">Admin</option>
                    <option value="0">Membre</option>
                </select>
            </div>         
        </div>
        <input type="submit" class="btn btn-success mt-3" value="Enregistrer">
    </form>

    <main class="container">
        
    </main>

<?php 
$content = ob_get_clean();

include "views/template.phtml";


