<?php ob_start(); ?>

<table class="table table-strepid">
    <tr class="table-dark">
        <td>Agence</td>
        <td>Titre</td>
        <td>Adresse</td>
        <td>Ville</td>
        <td>CP</td>
        <td>Description</td>
        <td>Image</td>
        <td>Action</td>
    </tr>

    <?php foreach ($agences as $agence): ?>
        <tr>
            <td> <?= $agence->getId_agence(); ?></td>
            <td> <?= $agence->getTitre(); ?></td>
            <td> <?= $agence->getAdresse(); ?></td>
            <td> <?= $agence->getVille(); ?></td>
            <td> <?= $agence->getCp(); ?></td>
            <td> <?= $agence->getDescription(); ?></td>
            <td> <?= $agence->getPhoto(); ?></td>
            <td>
                <a href="#">voir</a>
                <a href="#">Modifier</a>
                <a href="#">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

    <form action="" method="post" class="form-group">
        <div class="row">
            <div class="col-6 mt-4">
                <label for="titre">titre</label>
                <input type="text" name="titre" class="form-control" placeholder="titre de l'agence">
            </div>
            <div class="col-6 mt-4">
                <label for="adresse">Adresse</label>
                <input type="text" name="adresse" class="form-control" placeholder="Adresse">
            </div>
            <div class="col-6 mt-4">
                <label for="description">Description</label>
                <textarea name="description" id="description" cols="30" rows="10" placeholder="Description de votre agence"></textarea>
            </div>
            <div class="col-6 mt-4">
                <label for="ville">Ville</label>
                <input type="text" name="ville" class="form-control" placeholder="Ville">
            </div>
            <div class="col-6 mt-4">
                <label for="photo">Photo</label>
                <input type="file" name="photo" class="form-control" placeholder="photo">
            </div>
            
            <div class="col-6 mt-4">
                <label for="cp">Code Postal</label>
                <input type="text" name="cp" class="form-control" placeholder="Code Postal">
            </div>          
        </div>
        <input type="submit" class="btn btn-success mt-3" value="Enregistrer">
    </form>

    <main class="container">
        
    </main>

<?php 
$content = ob_get_clean();

include "views/template.phtml";


