<?php ob_start(); ?>

    <form action="" method="post" class="form-group">
        <div class="row">
            <div class="col-6 mt-4">
                <label for="titre">titre</label>
                <input type="text" name="titre" class="form-control" placeholder="titre de l'agence">
            </div>
            <div class="col-6 mt-4">
                <label for="adresse">Adresse</label>
                <input type="text" name="adresse" class="form-control" placeholder="Adresse">
            </div>
            <div class="col-6 mt-4">
                <label for="description">Description</label>
                <textarea name="description" id="description" cols="30" rows="10" placeholder="Description de votre agence"></textarea>
            </div>
            <div class="col-6 mt-4">
                <label for="ville">Ville</label>
                <input type="text" name="ville" class="form-control" placeholder="Ville">
            </div>
            <div class="col-6 mt-4">
                <label for="photo">Photo</label>
                <input type="file" name="photo" class="form-control" placeholder="photo">
            </div>
            
            <div class="col-6 mt-4">
                <label for="cp">Code Postal</label>
                <input type="text" name="cp" class="form-control" placeholder="Code Postal">
            </div>          
        </div>
        <input type="submit" class="btn btn-success mt-3" value="Enregistrer">
    </form>

<?php 
$content = ob_get_clean();

include "views/template.phtml";


