<?php ob_start(); ?>

    <table class="table table-striped mt-3">
        <tr class="table-dark">
            <td>Id</td>
            <td>Agence</td>
            <td>Titre</td>
            <td>Marque</td>
            <td>Modele</td>
            <td>Description</td>
            <td>Photo</td>
            <td>Prix</td>
            <td>Action</td>
          </tr>

          <?php foreach($vehicules as $vehicule): ?>
               <tr>
                    <td> <?= $vehicule->getId_vehicule() ?> </td>
                    <td> <?= $vehicule->getId_agence() ?> </td>
                    <td> <?= $vehicule->getTitre() ?> </td>
                    <td> <?= $vehicule->getMarque() ?> </td>
                    <td> <?= $vehicule->getModele() ?> </td>
                    <td> <?= $vehicule->getDescription() ?> </td>
                    <td>
                        <img src="public/img/vehicule<?= $vehicule->getPhoto() ?>" class="img-fluid" alt="">
                    </td>
                    <td> <?= $vehicule->getPrix_journalier() ?> </td>
                    <td>
                         <a href="?actionVehicule=modifier&id=<?= $vehicule->getId_vehicule() ?>"><i class="fas fa-pen"></i></a>
                         &nbsp; - &nbsp;
                         <a href="?actionVehicule=supprimer&id=<?= $vehicule->getId_vehicule() ?>"><i class="fas fa-trash"></i></a>
                    </td>
               </tr>
          <?php endforeach; ?>

     </table>

     <form action="" method="post" enctype="multipart/form-data">
          <input type="hidden" name="id_vehicule" value="<?= isset($vehiculeActuelle) ? $vehiculeActuelle->getId_vehicule() : 0 ?>">
          
          <div class="row">
               <div class="col-6 mt-4">
                   <label for="id_agence">Agence</label>
                   <select name="id_agence" id="">
            <?php foreach($agences as $agence) : ?>
                    <option value="<?= $agence->getId_agence(); ?>"> <?= $agence->getId_agence(); ?> <?= $agence->getTitre(); ?></option>
                    <?php endforeach ?>
                   </select>
                   
          <div class="row">
               <div class="col-6 mt-4">
                   <label for="titre">Titre</label>
                   <input type="text" name="titre" class="form-control" placeholder="Titre" value="<?= isset($vehiculeActuelle) ? $vehiculeActuelle->getTitre() : '' ?>">
               </div>
               <div class="col-6 mt-4">
                   <label for="marque">Marque</label>
                   <input type="text" name="marque" class="form-control" placeholder="Marque" value="<?= isset($vehiculeActuelle) ? $vehiculeActuelle->getMarque() : '' ?>">
               </div>
               <div class="col-6 mt-4">
                   <label for="modele">Modele</label> 
                   <input type="text" name="modele" class="form-control" placeholder="Modele" value="<?= isset($vehiculeActuelle) ? $vehiculeActuelle->getModele() : '' ?>">
               </div>
               <div class="col-6 mt-4">
                   <label for="prix">Prix</label>
                   <input type="text" name="prix" class="form-control" placeholder="Prix" value="<?= isset($vehiculeActuelle) ? $vehiculeActuelle->getPrix_journalier() : '' ?>">
               </div>
               <div class="col-6 mt-4">
                   <label for="statut">Photo</label>
                   <input type="file" name="photo" class="form-control">

                    <?php if(isset($agenceActuelle)): ?>
                        <img src="public/img/vehicule/<?= $vehiculeActuelle->getPhoto() ?>" alt="">
                        <input type="hidden" name="photoActuelle" value="<?= $vehiculeActuelle->getPhoto() ?>">
                    <?php endif; ?>

               </div>  
               
               <div class="col-6 mt-4">
                <label for="mdp">Description</label>
                <textarea name="description" name="description" placeholder="Votre texte" class="form-control" cols="30" rows="10"><?= isset($vehiculeActuelle) ? $vehiculeActuelle->getDescription() : '' ?></textarea>
            </div>        
           </div>
           <input type="submit" class="btn btn-success mt-3">
     </form>

<?php
$content = ob_get_clean();

include "views/template.phtml";